ORDSYS-18: Добавить обработчик ошибок
SoldatovAlexandr/agreement-service pull request #9
Opened 2021-09-30 18:33 UTC by SoldatovAlexandr

2021-10-02 09:22 UTC, nvk66 requested changes

2021-10-02 09:22 UTC, nvk66 commented on src/main/resources/messages.properties
> +incorrect.phone.number.error=Требуемое значение указано неверно.
Если разносим на разные ошибки, то я бы и текст менял

2021-10-02 09:22 UTC, nvk66 commented on src/main/resources/messages.properties
> +exception.not.found=Нет данных.
Не удалось найти данные

2021-10-02 09:22 UTC, nvk66 commented on src/main/java/edu/strongsubgroup/agreement/api/exception/RestResponseEntityExceptionHandler.java
> +    private static final String DEFAULT_MESSAGE = "Уважаемый пользователь! Произошла непредвиденная ошибка.";
А почему используем констату, а не из пропертей берём. Там же есть такой те же текст ошибки.

2021-10-02 14:27 UTC, SoldatovAlexandr commented on src/main/resources/messages.properties
> +incorrect.phone.number.error=Требуемое значение указано неверно.
Есть задача под это отдельная.

2021-10-02 14:28 UTC, SoldatovAlexandr commented on src/main/java/edu/strongsubgroup/agreement/api/exception/RestResponseEntityExceptionHandler.java
> +    private static final String DEFAULT_MESSAGE = "Уважаемый пользователь! Произошла непредвиденная ошибка.";
Все сообщения берутся из пропертей, но если что-то идет не так, то берем дефолтное.  Так есть гарантия, что сообщение точно будет.

2021-10-03 02:44 UTC, merged

2021-10-03 07:57 UTC, SoldatovAlexandr commented on src/main/resources/messages.properties
> +exception.not.found=Нет данных.
Исправил